<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import type { Merchant } from '@local/types';
import MerchantCard from '../components/MerchantCard.vue';
import { getData } from '../lib/api'; import { demoMerchants } from '../data/demo';
const demoMode=import.meta.env.DEV;const route=useRoute(); const router=useRouter(); const keyword=ref(String(route.query.keyword??'')); const prefecture=ref(String(route.query.prefectureCode??'27')); const sort=ref('recommended'); const merchants=ref<Merchant[]>(demoMode?demoMerchants:[]); const loading=ref(false); const total=computed(()=>merchants.value.length);
async function load(): Promise<void> { loading.value=true; const params=new URLSearchParams(); if(keyword.value)params.set('keyword',keyword.value); params.set('prefectureCode',prefecture.value); if(route.query.categoryId)params.set('categoryId',String(route.query.categoryId)); params.set('sort',sort.value); try{const result=await getData<{items:Merchant[]}>(`/merchants/search?${params}`);merchants.value=result.items;}catch{merchants.value=demoMode?demoMerchants.filter(item=>!keyword.value||`${item.nameJa}${item.shortDescriptionJa}`.includes(keyword.value)):[];}finally{loading.value=false;} }
function submit():void{void router.replace({query:{...route.query,keyword:keyword.value,prefectureCode:prefecture.value}});void load();} watch(sort,()=>void load()); onMounted(load);
</script>
<template><section class="search-header"><span class="eyebrow">FIND YOUR LOCAL PRO</span><h1>お店・サービスを探す</h1><form class="search-bar" @submit.prevent="submit"><select v-model="prefecture"><option value="27">大阪府</option><option value="13">東京都</option><option value="26">京都府</option></select><input v-model="keyword" placeholder="店舗・サービスを検索"><button>検索</button></form></section><section class="search-layout"><aside><h3>絞り込み</h3><label>カテゴリ<select><option>すべてのカテゴリ</option><option>民泊清掃</option><option>ハウスクリーニング</option></select></label><label>距離<select><option>指定なし</option><option>3km以内</option><option>5km以内</option></select></label><label class="check"><input type="checkbox"> 営業中のみ</label><button class="text-button">条件をクリア</button></aside><div class="results"><div class="results-head"><b>{{ total }}件のお店</b><select v-model="sort"><option value="recommended">おすすめ順</option><option value="rating">評価が高い順</option><option value="popular">人気順</option><option value="newest">新着順</option></select></div><div v-if="loading" class="loading">お店を探しています…</div><div v-else-if="!merchants.length" class="empty"><b>条件に合うお店が見つかりませんでした</b><p>キーワードや地域を変えてお試しください。</p></div><div v-else class="merchant-grid two"><MerchantCard v-for="merchant in merchants" :key="merchant.id" :merchant="merchant" /></div></div></section></template>
